
export const posts = [
  {
      "id_tour": 4,
      "name_tour": "Hành Trình Khám Phá Đảo Phú Quốc",
      "id_manager": 4,
      "id_staff": 5,
      "departure_day": 123140,
      "departure": "17/5/2024",
      "end_tour_day": 123143,
      "end_tour": "20/5/2024",
      "destination": "Phú Quốc",
      "initial_price": 2200000,
      "promotional_price": 1800000,
      "promotional": 20,
      "introduce": "Đảo Phú Quốc, được biết đến với bãi biển xanh ngắt, cát trắng mịn và bờ biển dài không ngớt, là một trong những điểm đến nổi tiếng nhất của Việt Nam. Hành trình này sẽ dẫn bạn khám phá những bãi biển tuyệt vời như Sao, Kem, và Ông Lang, tham quan các điểm",
      "highlight": "Tận hưởng bình minh trên bãi biển Sao, tham gia các hoạt động thể thao dưới nước như lặn ngắm san hô, thưởng thức món hải sản tươi ngon tại chợ đêm Dinh Cậu, và tham quan Vườn Tiên và Suối Tranh.",
      "insurance": true,
      "bus": false,
      "bicycle": false,
      "taxi": false,
      "plane": true,
      "meal": true,
      "photos": "hthttps://th.bing.com/th/id/OSK.HERO2gpFHTqFuGUjy8rSeKw59FweRxc_Bo3_LACwGWsiS-E?rs=1&pid=ImgDetMain",
      "tour_guide": true,
      "createdAt": "2024-04-23T14:39:43.000Z",
      "updatedAt": "2024-04-23T14:39:43.000Z"
  },
  {
      "id_tour": 3,
      "name_tour": "Khám Phá Vùng Đất Cổ - Hành Trình Qua Thời Gian",
      "id_manager": 3,
      "id_staff": 4,
      "departure_day": 123129,
      "departure": "6/5/2024",
      "end_tour_day": 123135,
      "end_tour": "12/5/2024",
      "destination": "Huế - Hội An - Đà Nẵng",
      "initial_price": 1800000,
      "promotional_price": 1500000,
      "promotional": 15,
      "introduce": "Hành trình này sẽ đưa bạn trở lại thời gian, khám phá văn hóa và lịch sử rực rỡ của vùng Đất Cổ từ thời kỳ triều đại Phong Kiến đến thời kỳ hiện đại. Bạn sẽ được tham quan các di sản văn hóa thế giới tại thành phố cố Huế, khám phá những con đường cổ kính ",
      "highlight": "Tham quan Đại Nội và Lăng Tự Đức ở Huế, ngắm cầu ánh sao Nhật Lệ và thưởng thức ẩm thực đường phố tại Hội An, tận hưởng bình minh tại Bà Nà Hills và ngắm hoàng hôn tại bãi biển Mỹ Khê ở Đà Nẵng.",
      "insurance": true,
      "bus": true,
      "bicycle": false,
      "taxi": false,
      "plane": false,
      "meal": true,
      "photos": "https://th.bing.com/th/id/OSK.HERO2gpFHTqFuGUjy8rSeKw59FweRxc_Bo3_LACwGWsiS-E?rs=1&pid=ImgDetMain",
      "tour_guide": true,
      "createdAt": "2024-04-23T14:38:23.000Z",
      "updatedAt": "2024-04-23T14:38:23.000Z"
  },
  {
      "id_tour": 2,
      "name_tour": "Khám Phá Cao Nguyên Đá Đen",
      "id_manager": 2,
      "id_staff": 3,
      "departure_day": 123124,
      "departure": "30/4/2024",
      "end_tour_day": 123127,
      "end_tour": "3/5/2024",
      "destination": "Đà Lạt",
      "initial_price": 1200000,
      "promotional_price": 900000,
      "promotional": 25,
      "introduce": "Trải nghiệm văn hóa và thiên nhiên tại Cao Nguyên Đá Đen",
      "highlight": "Đi bộ trên đá đen, thăm vườn hoa và thác nước",
      "insurance": true,
      "bus": true,
      "bicycle": false,
      "taxi": false,
      "plane": false,
      "meal": true,
      "photos": "https://th.bing.com/th/id/OSK.HERO2gpFHTqFuGUjy8rSeKw59FweRxc_Bo3_LACwGWsiS-E?rs=1&pid=ImgDetMain",
      "tour_guide": true,
      "createdAt": "2024-04-23T14:37:30.000Z",
      "updatedAt": "2024-04-23T14:37:30.000Z"
  },
  {
      "id_tour": 1,
      "name_tour": "Du Lịch Đảo lý sơn",
      "id_manager": 1,
      "id_staff": 2,
      "departure_day": 123123,
      "departure": "23/4/2024",
      "end_tour_day": 123123,
      "end_tour": "25/4/2024",
      "destination": "Tam kỳ",
      "initial_price": 800000,
      "promotional_price": 400000,
      "promotional": 50,
      "introduce": "du lịch ngắm gái bá cháy",
      "highlight": "du lịch ngắm gái bá cháy",
      "insurance": true,
      "bus": true,
      "bicycle": true,
      "taxi": true,
      "plane": true,
      "meal": true,
      "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
      "tour_guide": true,
      "createdAt": "2024-04-23T14:35:47.000Z",
      "updatedAt": "2024-04-23T14:35:47.000Z"
  }, {
    "id_tour": 1,
    "name_tour": "Du Lịch Đảo lý sơn",
    "id_manager": 1,
    "id_staff": 2,
    "departure_day": 123123,
    "departure": "23/4/2024",
    "end_tour_day": 123123,
    "end_tour": "25/4/2024",
    "destination": "Tam kỳ",
    "initial_price": 800000,
    "promotional_price": 400000,
    "promotional": 50,
    "introduce": "du lịch ngắm gái bá cháy",
    "highlight": "du lịch ngắm gái bá cháy",
    "insurance": true,
    "bus": true,
    "bicycle": true,
    "taxi": true,
    "plane": true,
    "meal": true,
    "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
    "tour_guide": true,
    "createdAt": "2024-04-23T14:35:47.000Z",
    "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}, {
  "id_tour": 1,
  "name_tour": "Du Lịch Đảo lý sơn",
  "id_manager": 1,
  "id_staff": 2,
  "departure_day": 123123,
  "departure": "23/4/2024",
  "end_tour_day": 123123,
  "end_tour": "25/4/2024",
  "destination": "Tam kỳ",
  "initial_price": 800000,
  "promotional_price": 400000,
  "promotional": 50,
  "introduce": "du lịch ngắm gái bá cháy",
  "highlight": "du lịch ngắm gái bá cháy",
  "insurance": true,
  "bus": true,
  "bicycle": true,
  "taxi": true,
  "plane": true,
  "meal": true,
  "photos": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/noauth/oOyESsuJRjeXCepd9S7ER.jpeg?w=200&h=200&f=face",
  "tour_guide": true,
  "createdAt": "2024-04-23T14:35:47.000Z",
  "updatedAt": "2024-04-23T14:35:47.000Z"
}
];
